title: Bas Doorn
domain: doorn.dev
author: Bas Doorn
email: "'basdoorn.nl'.replace('a', '@')"
email_placeholder: basdoorn
pgp: D7FBED77
description: >-
  I'm Bas Doorn and this is my personal website.
footer_text: >-
  Want to get in touch or book me as a speaker for your (online) event? Feel free to send me an email.
baseurl: ""
url: "https://doorn.dev"
twitter_username: '0xba5d'
github_username: bas-d
linkedin_username: bas-doorn-50b9935a

header_pages:
  - pages/about.md
  - pages/resources.html

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
